---
title: Accomodation
output: 
  html_document:
    toc: true
    toc_float: true
---
<style>
  .title{
    display: none;
  }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 40px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 80px;
  padding: 20px 0;
  background-color: #2c3e50;
  text-align: center;
}
```

```{js, echo=FALSE}
$(function() {
  $('.main-container').after($('.footer'));
})
```
<style>
body {
text-align: left}
</style>

## HOTEL INFORMATION

<a href="https://www.cataloniahotels.com/en/hotel/catalonia-la-pedrera" target="_blank"><span style="font-size:calc(12px + 1vw)">Hotel Catalonia La Pedrera</span></a>

This hotel is located next to Avinguda Diagonal and Passeig de Gràcia, ideal for shopping. Guests can easily access Plaza Cataluña and the city’s historic gothic quarter. Free Wi-Fi is available.

Located along the modernist route, Hotel Catalonia La Pedrera is surrounded by much of the interesting architecture that Barcelona is famous for, such as Gaudí and Domenech i Muntaner's key buildings, including La Pedrera.

A set menu is available at the on-site restaurant; room service is also available.

Guests can easily enjoy this cosmopolitan city as Hotel Catalonia La Pedrera is within walking distance of Barcelona’s many attractions. As well as the excellent public transport links providing swift access to the entire city and the surrounding area, the hotel offers great value for money. The hotel also includes meeting amenities and conference rooms available for business events and banquets.
<br>
<br>
<br>





::: {.footer .text-muted .bg-info}
 <p>SAPFLUXNET Core Team<br>
 <a href="mailto:sapfluxnet@creaf.uab.cat">sapfluxnet@creaf.uab.cat</a></p>
:::