---
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 40px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 80px;
  padding: 20px 0;
  background-color: #2c3e50;
  text-align: center;
}
body{margin-top:20px;}
.idance .classes-details ul.timetable {
    margin: 0 0 22px;
    padding: 0;
}
.cd-schedule__group > ul {
  position: relative;
  padding: 0 var(--component-padding);
  display: flex;
  overflow-x: scroll;
  -webkit-overflow-scrolling: touch;
}

```

```{js, echo=FALSE}
$(function() {
  $('.main-container').after($('.footer'));
})

```

## SCHEDULE
Find the updated schedule [here](./schedule_page.html).

Note that this schedule may change
Talks

  
Talks should be about 15-20 minutes long, after which will be time for discussion.

## TALKS

Jake Nelson - *ecosystem to global scale*
Markus Reichstein - Introduction to transpiration science at BGC
Elke Eichelmann - The unique challenges of partitioning ET in flooded ecosystems: From leaf level to ecosystem scale
Madi Amer - Resilience to draught and ET partitioning in semi-arid ecosystems
Luke Smallman - *ecosystem to global scale*
Russ Scott - Using flux tower water and carbon flux data to determine evapotranspiration partitioning.
Diego Miralles - Potential of satellite sun-induced fluorescence to enhance understanding of transpiration: from ecosystem to global scales
Rafael Poyatos - Towards stand transpiration estimates from global sap flow measurements
Victor Flo - Global variation of tree transpiration responses to vapor pressure deficit and soil water content
William Schlesinger - Transpiration and the global water cycle
Paul Stoy - *grasslands and both dryland and irrigated agroecosystems*
Mirco Migliavacca - Constraining Evapotranspiration partitioning with multiple data streams in the MANIP project



::: {.footer .text-muted .bg-info}
 <p>SAPFLUXNET Core Team<br>
 <a href="mailto:sapfluxnet@creaf.uab.cat">sapfluxnet@creaf.uab.cat</a></p>
:::