---
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{css, echo=FALSE}
html {
  position: relative;
  min-height: 100%;
}
body {
  margin-bottom: 40px;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 80px;
  padding: 20px 0;
  background-color: #2c3e50;
  text-align: center;
}
```

```{js, echo=FALSE}
$(function() {
  $('.main-container').after($('.footer'));
})
```
## TRAVEL INFORMATION

## Getting to Barcelona by train from el Prat Airport
<br>
<br>
<br>

## Getting to Can Balasc from Barcelona

```{r out.width='100%', echo=FALSE}
library(leaflet)
leaflet() %>% addTiles() %>%
  setView(2.078, 41.4300, zoom = 12) %>%
  addPopups(
    2.078, 41.4300,
    'Here is <b>Can Balasc</b>'
  )
```

Can Balasc ([CREAF](http://www.creaf.cat/))
<br>
<br>
<br>

## Getting to CREAF from Barcelona
<br>
<br>


::: {.footer .text-muted .bg-info}
 <p>SAPFLUXNET Core Team<br>
 <a href="mailto:sapfluxnet@creaf.uab.cat">sapfluxnet@creaf.uab.cat</a></p>
:::